apiVersion: core.hybridapp.io/v1alpha1
kind: PlacementRule
metadata:
  name: board
spec:
  replicas: 1
  decisionWeight: 5
  targetLabels:
    matchLabels:
      cloud: IBM
  advisors:
  - name: alphabet    
    weight: 60
  - name: veto
    type: predicate
    weight: 50
    rules:
      resources:
      - name: raleigh
        namespace: raleigh
