apiVersion: core.hybridapp.io/v1alpha1
kind: PlacementRule
metadata:
  name: board
spec:
  replicas: 1
  targetLabels:
    matchLabels:
      cloud: IBM
  advisors:
  - name: alphabet    
    weight: 50
  - name: veto
    weight: 50
    rules:
      resources:
      - name: raleigh
        namespace: raleigh
      - name: toronto
        namespace: toronto
